language: java
sudo: false # faster builds
before_install:
  - sudo apt-get install jq
install: mvn install
jdk:
  - oraclejdk8
script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

